# Author: Samir Ranjan Parhi
# License: Same as Repository Licence
# Usage : Production Grade
version: '3'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: InitMongo@597
      MONGO_INITDB_ROOT_PASSWORD: InitPwd@658
    ports:
      - "27017:27017"
    networks:
      - grafana-net

  # Grafana Service
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin@365
      GF_SECURITY_ADMIN_USER: admin
      GF_DATABASE_TYPE: mongodb
      GF_DATABASE_HOST: mongodb:27017
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana_db_mongo
      GF_DATABASE_PASSWORD: your_grafana_passwd
    ports:
      - "3000:3000"
    networks:
      - grafana-net
    depends_on:
      - mongodb

networks:
  grafana-net:
    driver: bridge
