name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarqube_scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Start SonarQube
      run: docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube:latest

    - name: Wait for SonarQube to start
      run: docker exec sonarqube sh -c "while ! nc -z localhost 9000; do sleep 1; done"

    - name: SonarQube Scan
      run: docker run --rm -e SONAR_HOST_URL=http://localhost:9000 -e SONAR_LOGIN=admin -e SONAR_PASSWORD=admin sonarsource/sonar-scanner-cli:latest

    - name: Stop SonarQube
      run: docker stop sonarqube
